services:
  - name: forward-to-admin-bot
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        fromSecret: bot_token
      - key: ADMIN_ID
        fromSecret: admin_id
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: forward-to-admin-bot
          property: service.host
