services:
  - type: web
    name: forward-to-admin-bot
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        value: 7435442778:AAGazu-HC0za77yUk0QJGnKWM6eqKiEuyU8
      - key: ADMIN_ID
        value: 6980954709
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: forward-to-admin-bot
          property: service.host
